ASP_Restaurant/Controllers/ShoppingCartController.cs
using ASP_Restaurant.DAL;
using ASP_Restaurant.Models;
using ASP_Restaurant.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASP_Restaurant.Controllers
{
    public class ShoppingCartController : Controller
    {
        private ASP_RestaurantContext db = new ASP_RestaurantContext();

        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };

            return View(viewModel);
        }

        public ActionResult AddToCart(int id)
        {
            var addedProduct = db.Products.Single(product => product.Id == id);

            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedProduct);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            string productName = db.Carts.FirstOrDefault(item => item.ProductId == id).Product.Name;

            int itemCount = cart.RemoveFromCart(id);

            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(productName) + " Zostalo usuniete z Twojego koszyka",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };

            return Json(results);
        }

        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

ASP_Restaurant/Controllers/StoreFrontController.cs
using ASP_Restaurant.DAL;
using ASP_Restaurant.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ASP_Restaurant.Controllers
{
    public class StoreFrontController : Controller
    {
        private ASP_RestaurantContext db = new ASP_RestaurantContext();
        // GET: StoreFront
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }
    }
}

ASP_Restaurant/Views/StoreFront/Index.cshtml
@model ASP_Restaurant.Models.Category
@{
    ViewBag.Title = @Model.Name;
}

<br />
<br />
<div class="row">
    <div class="col-xs-12 col-md-3">
        <ul class="nav nav-pills nav-stacked">
            @if (Model.Name == "Napoje")
            {
                <li class="active">
                    <a href="~/StoreFront/Index/2">Napoje</a>
                </li>
            }
            else
            {
                <li>
                    <a href="~/StoreFront/Index/2">Napoje</a>
                </li>
            }
            @if (Model.Name == "Dania Glowne")
            {
                <li class="active">
                    <a href="~/StoreFront/Index/3">Dania Glowne</a>
                </li>
            }
            else
            {
                <li>
                    <a href="~/StoreFront/Index/3">Dania Glowne</a>
                </li>
            }
            @if (Model.Name == "Deser")
            {
                <li class="active">
                    <a href="~/StoreFront/Index/4">Desery</a>
                </li>
            }
            else
            {
                <li>
                    <a href="~/StoreFront/Index/4">Desery</a>
                </li>
            }
            @if (Model.Name == "Zupa")
            {
                <li class="active">
                    <a href="~/StoreFront/Index/5">Zupy</a>
                </li>
            }
            else
            {
                <li>
                    <a href="~/StoreFront/Index/5">Zupy</a>
                </li>
            }

        </ul>
    </div>
    <div class="col-xs-12 col-md-9">
        <div class="row">
            @foreach (var product in Model.Products)
            {
                <div class="col-xs-12 col-md-3">
                    <div class="thumbnail">
                        <img class="img-responsive" src="~/Content/Images/Products/@(product.Name).png">
                        <div class="caption text-center">
                            <p>
                                <b>Nazwa:</b> <span>@product.Name</span>
                            </p>
                            <p>
                                <b>Cena:</b> <span>@product.Price zł</span>
                            </p>
                            <p class="text-center">
                                @Html.ActionLink("Dodaj do koszyka", "AddToCart", "ShoppingCart", new { id = product.Id }, new { @class = "btn btn-info" })
                            </p>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>